### ISSUE TITLE
Update Experience

### ISSUE THREAD

**Issue by akshat157** [akshat157/akshat157.github.io#2]
Experience section outdated. Needs update.

**Comment by LON3WO7F** [comment]
Hey @akshat157 
Please elaborate more.

**Comment by akshat157** [comment]
Hi @LON3WO7F !
Sorry, this is my personal website repository. I maintain a few other projects which I wanted to make Hacktoberfest compatible.
I was actually trying to understand the rule changes they have done this year before I open issues in the other projects.

I see you work with JS as well. Do checkout my other projects in a while when I make them Hacktoberfest compatible! :)
